2016-06-10 15:31:55.305 -0600	START		Running CalculatorTesting.feature
2016-06-10 15:31:55.655 -0600	imagefound	Calculator	found at (716, 172)	2	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:55.744 -0600	click		at (716, 172)	6	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:55.745 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:31:55.747 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:31:56.644 -0600	click	CalcClearButton	at (780, 316)	2	on_there_is_no_current_value_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:56.646 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:31:56.648 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:31:57.373 -0600	typetext		4[return]	3	on_i_enter_num___num_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:57.374 -0600	LogSuccess		I enter 2 + 2 in the calculator
2016-06-10 15:31:57.375 -0600	LogSuccess		I enter 2 + 2 in the calculator
2016-06-10 15:31:58.924 -0600	readtext		(682,212,878,268)
2016-06-10 15:31:58.926 -0600	LogSuccess		value is correct	4	on_the_value_returned_should_be_4	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:58.928 -0600	LogSuccess		the value returned should be 4
2016-06-10 15:31:58.929 -0600	LogSuccess		the value returned should be 4
2016-06-10 15:31:59.300 -0600	imagefound	Calculator	found at (716, 172)	2	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:59.389 -0600	click		at (716, 172)	6	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:31:59.389 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:31:59.390 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:32:00.294 -0600	click	CalcClearButton	at (780, 316)	2	on_there_is_no_current_value_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:00.295 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:32:00.296 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:32:01.022 -0600	typetext		6[return]	3	on_i_enter_num_minus_num_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:01.023 -0600	LogSuccess		I enter 10 minus 4 in the calculator
2016-06-10 15:32:01.024 -0600	LogSuccess		I enter 10 minus 4 in the calculator
2016-06-10 15:32:02.497 -0600	readtext		(682,212,878,268)
2016-06-10 15:32:03.356 -0600	readtext		(682,212,878,268)
2016-06-10 15:32:03.356 -0600	Log		6	3	on_the_value_returned_should_be_6	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:03.359 -0600	LogSuccess		value is correct	5	on_the_value_returned_should_be_6	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:03.360 -0600	LogSuccess		the value returned should be 6
2016-06-10 15:32:03.361 -0600	LogSuccess		the value returned should be 6
2016-06-10 15:32:03.748 -0600	imagefound	Calculator	found at (716, 172)	2	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:03.840 -0600	click		at (716, 172)	6	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:03.841 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:32:03.842 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 15:32:05.095 -0600	click	CalcClearButton	at (780, 316)	2	on_there_is_no_current_value_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:05.097 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:32:05.098 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 15:32:14.440 -0600	typetext		5	8	on_i_multiply_numbernum_by_numbernum_in_the_calculator_app	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:15.156 -0600	typetext		*	9	on_i_multiply_numbernum_by_numbernum_in_the_calculator_app	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:15.896 -0600	typetext		40[return]	10	on_i_multiply_numbernum_by_numbernum_in_the_calculator_app	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:15.897 -0600	LogSuccess		I multiply Number1 by Number2 in the calculator app
2016-06-10 15:32:15.898 -0600	LogSuccess		I multiply Number1 by Number2 in the calculator app
2016-06-10 15:32:17.427 -0600	readtext		(682,212,878,268)
2016-06-10 15:32:17.429 -0600	LogError		Fail! bad calculation!	7	on_the_app_displays_the_correct_answer	CalculatorTesting.script<SOURCE>
2016-06-10 15:32:17.432 -0600	LogSuccess		the app displays the correct answer
2016-06-10 15:32:17.433 -0600	LogSuccess		the app displays the correct answer
2016-06-10 15:32:17.435 -0600	EndTestCase		(Duration:"22.127959", Errors:"1", Exceptions:"0", StartTime:"2016-06-10 15:31:55 -0600", Successes:"26", TestCase:"CalculatorTesting.feature", Warnings:"0")
2016-06-10 15:32:17.890 -0600	FAILURE	Screen_Error.png	3 scenarios (0 failed, 3 passed) 12 steps (0 failed, 0 skipped, 12 passed) Execution Time 0:00:22
