2016-06-10 13:57:37.863 -0600	START		Running CalculatorTesting.feature
2016-06-10 13:57:38.251 -0600	imagefound	Calculator	found at (563, 224)	2	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:38.335 -0600	click		at (563, 224)	6	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:38.336 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 13:57:38.337 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 13:57:39.239 -0600	click	CalcClearButton	at (627, 368)	2	on_there_is_no_current_value_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:39.241 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 13:57:39.241 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 13:57:39.965 -0600	typetext		4[return]	3	on_i_enter_num___num_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:39.966 -0600	LogSuccess		I enter 2 + 2 in the calculator
2016-06-10 13:57:39.967 -0600	LogSuccess		I enter 2 + 2 in the calculator
2016-06-10 13:57:41.528 -0600	readtext		(529,264,725,320)
2016-06-10 13:57:41.530 -0600	LogSuccess		value is correct	6	on_the_value_returned_should_be_4	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:41.531 -0600	LogSuccess		the value returned should be 4
2016-06-10 13:57:41.532 -0600	LogSuccess		the value returned should be 4
2016-06-10 13:57:41.922 -0600	imagefound	Calculator	found at (563, 224)	2	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:42.012 -0600	click		at (563, 224)	6	on_that_the_calculator_app_is_running_and_in_focus	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:42.013 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 13:57:42.013 -0600	LogSuccess		that the Calculator app is running and in focus
2016-06-10 13:57:43.308 -0600	click	CalcClearButton	at (627, 368)	2	on_there_is_no_current_value_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:43.310 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 13:57:43.311 -0600	LogSuccess		there is no current value in the calculator
2016-06-10 13:57:44.036 -0600	typetext		6[return]	3	on_i_enter_num_minus_num_in_the_calculator	CalculatorTesting.script<SOURCE>
2016-06-10 13:57:44.037 -0600	LogSuccess		I enter 10 minus 4 in the calculator
2016-06-10 13:57:44.038 -0600	LogSuccess		I enter 10 minus 4 in the calculator
2016-06-10 13:57:44.039 -0600	LogError		the value returned should be 6
2016-06-10 13:57:44.040 -0600	LogSuccess		the value returned should be 6
2016-06-10 13:57:44.041 -0600	EndTestCase		(Duration:"6.176886", Errors:"2", Exceptions:"0", StartTime:"2016-06-10 13:57:37 -0600", Successes:"16", TestCase:"CalculatorTesting.feature", Warnings:"0")
2016-06-10 13:57:44.534 -0600	FAILURE	Screen_Error.png	2 scenarios (1 failed, 1 passed) 8 steps (1 failed, 0 skipped, 7 passed) Execution Time 0:00:06
