<?xml version="1.0"?>
<testsuites>
 <testsuite name="CalculatorTesting.feature" package="gherkin.suite" timestamp="2016-06-13 09:31:38.038 -0600"
 tests="1" successes="11" errors="12" time="0.207000">
  <properties>
   <property name="RunDate" value="2016-06-13 09:31:38.038 -0600"/>
   <property name="Status" value="Failure"/>
  </properties>
  <testcase name="CalculatorTesting.feature" assertions="23" successes="11" errors="12" time="0.199">
    <failure type="LogError">that the Calculator app is running and in focus</failure>
    <failure type="LogError">there is no current value in the calculator</failure>
    <failure type="LogError">I enter 2 + 2 in the calculator</failure>
    <failure type="LogError">the value returned should be 4</failure>
    <failure type="LogError">that the Calculator app is running and in focus</failure>
    <failure type="LogError">there is no current value in the calculator</failure>
    <failure type="LogError">I enter 10 minus 4 in the calculator</failure>
    <failure type="LogError">the value returned should be 6</failure>
    <failure type="LogError">that the Calculator app is running and in focus</failure>
    <failure type="LogError">there is no current value in the calculator</failure>
    <failure type="LogError">the app displays the correct answer</failure>
  </testcase>
 </testsuite>
</testsuites>
