2016-06-14 11:07:04.004 -0600	START		Running CalcAppTesting.feature
2016-06-14 11:07:04.004 -0600	Exception		Remote Connection Unavailable	2	on_that_the_calculator_app_is_running_and_in_focus	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-14 11:07:04.004 -0600	LogError		that the Calculator app is running and in focus
2016-06-14 11:07:04.004 -0600	Exception		Remote Connection Unavailable	2	on_there_is_no_current_value_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-14 11:07:04.004 -0600	LogError		there is no current value in the calculator
2016-06-14 11:07:04.004 -0600	LogSuccess		I enter the first number in the calculator
2016-06-14 11:07:04.004 -0600	LogSuccess		I click the plus button ok
2016-06-14 11:07:04.004 -0600	LogWarning		I enter the second number ok
2016-06-14 11:07:04.004 -0600	LogWarning		I click the equals button
2016-06-14 11:07:04.004 -0600	LogWarning		the value displayed should be the correct sum for the two numbers entered
2016-06-14 11:07:04.004 -0600	EndTestCase		(Duration:"0.185", Errors:"3", Exceptions:"2", StartTime:"2016-06-14 11:07:04 -0600", Successes:"2", TestCase:"CalcAppTesting.feature", Warnings:"3")
2016-06-14 11:07:04.004 -0600	FAILURE		1 scenarios (1 failed, 0 passed) 7 steps (2 failed, 3 skipped, 2 passed) Execution Time 0:00:00
